name: nimble_leaves
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 1.0.0
  intl: ^0.15.0
  shimmer: ^1.0.0
 
  # flutter_webview_plugin: ^0.3.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_search: ^0.2.8
  flushbar: ^1.2.0
  percent_indicator: "^1.0.11" 
  custom_radio: ^0.1.2
  flutter_calendar_carousel: ^1.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  
  - assests/images/toastershadow.png
  - assests/images/g.png
  - assests/images/login-ipad.png
  - assests/images/logo-ipad.png
  - assests/images/login.png
  - assests/images/logo.png
  - assests/images/shadow.png


  fonts:
    - family: CustomIcons
      fonts:
        - asset: assests/fonts/CustomIcons.ttf

    - family: SairaSemiCondensed
      fonts:
        - asset: assests/fonts/SairaSemiCondensed-Black.ttf
        - asset: assests/fonts/SairaSemiCondensed-Bold.ttf
          weight: 900   
        - asset: assests/fonts/SairaSemiCondensed-ExtraBold.ttf
        - asset: assests/fonts/SairaSemiCondensed-ExtraLight.ttf
        - asset: assests/fonts/SairaSemiCondensed-Light.ttf
        - asset: assests/fonts/SairaSemiCondensed-Medium.ttf
          weight: 300
        - asset: assests/fonts/SairaSemiCondensed-Regular.ttf
        - asset: assests/fonts/SairaSemiCondensed-Thin.ttf
        - asset: assests/fonts/SairaSemiCondensed-Black.ttf
        - asset: assests/fonts/SairaSemiCondensed-SemiBold.ttf
    
        

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-assests/images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-assests/images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    # - family: Schyler
    #   fonts:
    #     - asset: assests/fonts/Schyler-Regular.ttf
    #     - asset: assests/fonts/Schyler-Italic.ttf
    #       style: italic
       
   
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-assests/fonts/#from-packages
