/// Flutter icons CustomIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData menunew = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData dashboard = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData employee = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData employee_inactive = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData reports = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData unplanned = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData planned = const IconData(0xe808, fontFamily: _kFontFam);
}
